import Link from "next/link";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Reveal from "@/components/Reveal";
import Story from "@/components/Story";
import Visual from "@/components/Visual";
import { site } from "@/lib/site";

export default function Home(){
 const schema={"@context":"https://schema.org","@type":site.businessType,"name":site.name,"url":site.url,"description":"Café de especialidad, desayunos y brunch en un espacio pensado para disfrutar sin prisa. Seleccionamos cafés con trazabilidad y ajustamos cada receta a su origen.","areaServed":site.city,"makesOffer":site.services.map(s=>({"@type":"Offer","itemOffered":{"@type":"Service","name":s.title}}))};
 return <><NavBar/><main>
 <section className="hero"><div className="hero-orb"/><div className="shell hero-grid"><div className="hero-copy"><p className="eyebrow">CAFÉ DE ESPECIALIDAD · MADRID</p><h1>Una taza que empieza mucho antes del primer sorbo.</h1><p className="lead">Café de especialidad, desayunos y brunch en un espacio pensado para disfrutar sin prisa. Seleccionamos cafés con trazabilidad y ajustamos cada receta a su origen.</p><div className="hero-actions"><Link className="button primary" href="/contacto">Descubre la carta</Link><Link className="button ghost" href="#servicios">Ver servicios</Link></div></div><div className="hero-art"><Visual stage={0}/></div></div><div className="shell stats"><div><strong>86+</strong><span>Puntos SCA</span></div><div><strong>03</strong><span>Orígenes rotativos</span></div><div><strong>100%</strong><span>Trazabilidad</span></div></div></section>
 <section id="servicios" className="section shell"><Reveal><p className="eyebrow">SERVICIOS</p><h2 className="display">Contenido útil para usuarios y buscadores.</h2><p className="section-intro">Cada servicio dispone de su propia URL, encabezado principal, texto especializado, metadatos y enlazado interno. La estructura está pensada para crecer con nuevas zonas o servicios.</p></Reveal><div className="service-grid"><Link href="/servicios/cafe-especialidad" className="service-card"><span>01</span><h3>Café de especialidad en Madrid</h3><p>Espresso, filtro y cafés de temporada preparados con recetas ajustadas a cada origen.</p><b>Ver servicio →</b></Link><Link href="/servicios/desayunos-brunch" className="service-card"><span>02</span><h3>Desayunos y brunch en Madrid</h3><p>Tostadas, opciones dulces y platos de brunch pensados para acompañar nuestro café de especialidad.</p><b>Ver servicio →</b></Link><Link href="/servicios/cafe-para-llevar" className="service-card"><span>03</span><h3>Café para llevar en Madrid</h3><p>Café preparado al momento para llevar, con espresso, bebidas con leche y opciones de filtro.</p><b>Ver servicio →</b></Link></div></section>
 <Story/>
 <section className="section shell"><div className="split-title"><p className="eyebrow">POSICIONAMIENTO ORGÁNICO</p><h2>SEO que empieza por explicar bien el servicio.</h2></div><div className="seo-grid"><Reveal className="seo-card"><h3>Café con trazabilidad y perfiles diferentes</h3><p>Trabajamos con lotes de temporada y contamos su origen, variedad y proceso para que puedas elegir por sabor y no solo por intensidad. La carta cambia cuando encontramos un café que aporta algo nuevo.</p></Reveal><Reveal className="seo-card"><h3>Espresso, filtro y una carta para quedarse</h3><p>La experiencia no termina en la máquina. Cuidamos el espacio, el ritmo del servicio y una carta breve de desayunos y brunch para acompañar cada café sin convertirlo en un producto secundario.</p></Reveal></div></section>
 <section className="cta-band"><div className="shell"><p className="eyebrow">MADRID</p><h2>Café de especialidad, tostado con calma.</h2><p>La ubicación, la marca y los datos de contacto están centralizados para que puedas adaptar esta plantilla a un proyecto real.</p><Link className="button light" href="/contacto">Solicitar información</Link></div></section>
 </main><Footer/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></>
}
