import Link from "next/link";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Reveal from "@/components/Reveal";
import Story from "@/components/Story";
import BrewStory from "@/components/BrewStory";
import Visual from "@/components/Visual";
import { site } from "@/lib/site";

export default function Home(){const schema={"@context":"https://schema.org","@type":site.businessType,"name":site.name,"url":site.url,"description":"Café de especialidad, desayunos y brunch en Madrid, con cafés de temporada y recetas ajustadas a cada origen.","areaServed":site.city,"makesOffer":site.services.map(s=>({"@type":"Offer","itemOffered":{"@type":"Service","name":s.title}}))};return <><NavBar/><main>
 <section className="hero coffee-hero"><div className="coffee-blob blob-a"/><div className="coffee-blob blob-b"/><div className="shell hero-grid"><div className="hero-copy"><p className="eyebrow">BRUMA · SPECIALTY COFFEE · MADRID</p><h1>Café con origen.<br/><em>Sabor con historia.</em></h1><p className="lead">Una cafetería de especialidad donde cada taza conecta finca, tueste, receta y momento. Espresso, filtro, desayunos y brunch preparados sin prisa.</p><div className="hero-actions"><Link className="button primary" href="/servicios/cafe-especialidad">Ver el café</Link><Link className="button ghost" href="#story">Seguir el viaje ↓</Link></div></div><div className="hero-art"><Visual/><div className="bean-note n1">floral</div><div className="bean-note n2">cacao</div><div className="bean-note n3">cítrico</div></div></div><div className="shell coffee-ticker"><span>ETHIOPIA</span><i>✦</i><span>COLOMBIA</span><i>✦</i><span>KENYA</span><i>✦</i><span>ESPRESSO</span><i>✦</i><span>FILTER</span></div></section>
 <section id="servicios" className="section shell cafe-services"><Reveal><p className="eyebrow">PARA QUEDARTE · PARA LLEVAR</p><h2 className="display">Una carta corta, viva y pensada alrededor del café.</h2></Reveal><div className="service-grid"><Link href="/servicios/cafe-especialidad" className="service-card"><span>01 / BEBIDA</span><h3>Café de especialidad</h3><p>Espresso, flat white y filtro con lotes rotativos y recetas calibradas cada día.</p><b>Explorar →</b></Link><Link href="/servicios/brunch-en-madrid" className="service-card"><span>02 / MESA</span><h3>Brunch en Madrid</h3><p>Una página de servicio específica para búsquedas de brunch, con café de especialidad como hilo conductor.</p><b>Explorar →</b></Link><Link href="/servicios/cafe-para-llevar" className="service-card"><span>03 / GO</span><h3>Café para llevar</h3><p>La misma precisión de barra, en un formato que sigue tu ritmo.</p><b>Explorar →</b></Link></div><div className="all-services-link"><Link className="button ghost" href="/servicios">Ver todos los servicios SEO →</Link></div></section>
 <Story/>
 <section className="section shell tasting-section"><div><p className="eyebrow">NOTAS DE CATA</p><h2>El sabor también se puede leer.</h2></div><div className="tasting-orbit"><span className="taste t1">Cacao</span><span className="taste t2">Jazmín</span><span className="taste t3">Melocotón</span><span className="taste t4">Caramelo</span><div className="taste-core">BRUMA<br/><small>seasonal</small></div></div><div className="tasting-copy"><p>Los descriptores no son ingredientes añadidos. Son referencias aromáticas que ayudan a explicar lo que encontramos de forma natural en el café.</p></div></section>
 <BrewStory/>
 <section id="seo-local" className="section shell seo-cafe"><Reveal><p className="eyebrow">CAFETERÍA DE ESPECIALIDAD EN MADRID</p><h2 className="display">SEO local con páginas útiles, no con texto de relleno.</h2><p className="section-intro">La estructura incluye una pestaña de servicios y páginas independientes para Brunch en Madrid, Desayunos en Madrid, Café de especialidad, Café para llevar y Café de filtro. Cada URL tiene metadatos, canonical, Schema.org y enlazado interno, y puede crecer con carta, horarios, ubicación y contenido real del negocio.</p></Reveal></section>
 <section className="cta-band"><div className="shell"><p className="eyebrow">YOUR DAILY RITUAL</p><h2>Tu próxima taza empieza aquí.</h2><Link className="button light" href="/contacto">Conocer BRUMA</Link></div></section>
 </main><Footer/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></>}
